version: "3.6"

services:
  postgres:
    image: postgres:16.2
    hostname: db_server
    container_name: db_server
    ports:
      - 5432:5432 
    environment:
      POSTGRES_DB: "ComputerCompany"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ComputerCompany"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped